FROM python:3.11-slim

ENV POETRY_VERSION=1.8.2

RUN apt-get update && apt-get install -y curl \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && ln -s /root/.local/bin/poetry /usr/local/bin/poetry \
    && poetry config virtualenvs.create false

WORKDIR /app
COPY pyproject.toml poetry.lock* ./
RUN poetry install --no-root

COPY . .

CMD ["uvicorn", "bonus_service.app.adapters.api.main:app", "--host", "0.0.0.0", "--port", "8000"]